name: Banking Survey 2023
description: This GitHub issue form is for the Banking Survey 2023
title: "[Banking Survey 2023]: "
labels: ["Banking Survey 2023"]
assignees:
  - yourGitHubUsername
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit the Banking Survey 2023!
  - type: dropdown
    id: frequency
    attributes:
      label: How often do you visit the bank in a month?
      options:
        - label: Once
          value: once
        - label: Twice
          value: twice
        - label: Thrice
          value: thrice
    validations:
      required: true
  - type: checkboxes
    id: services
    attributes:
      label: Which of the following banking services do you use regularly? (Select all that apply)
      options:
        - label: ATM services
          value: atm
        - label: Online banking
          value: online
        - label: Branch visits
          value: branch
        - label: Mobile banking
          value: mobile
    validations:
      required: true
  - type: textarea
    id: satisfaction
    attributes:
      label: How satisfied are you with the services provided by the bank?
    validations:
      required: true
  - type: dropdown
    id: recommend
    attributes:
      label: Would you recommend this bank to others?
      options:
        - label: Yes
          value: yes
        - label: No
          value: no
    validations:
      required: true
  - type: textarea
    id: improvement
    attributes:
      label: What improvements or additional services would you like to see from the bank?
    validations:
      required: true
