name: Local Languages Survey 2023 GitHub Actions workflow
run-name: Local Languages 2023 GitHub Actions
on:
  issues:
    types: [opened, edited]

jobs:
  issue_opened_edited:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Print issue details
        run: |
          echo Gotcha issue $LABELS
        env:
          LABELS: ${{ github.event.issue.labels[0].name }}

      - name: Checkout so that we have the python script in the container
        uses: actions/checkout@v2
        with:
          repository: pavankumar0077/Local-Language-for-Workflows
          token: ${{ secrets.GIT_TOKEN }}

      - name: View the github context
        run: echo "$GITHUB_CONTEXT" >> issue.out
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Push to neo4j
        run: |
          python -m pip install --upgrade pip
          pip install neo4j
          python ${{ vars.SCRIPTS_DIR }}/PushRecordToNeo4j.py
        env:
          NEO4J_URI: ${{ secrets.NEO4J_URL }}
          NEO4J_USER: ${{ secrets.NEO4J_USER }}
          NEO4J_PASSWD: ${{ secrets.NEO4J_PASSWD }}
          SCRIPTS_DIR: ${{ vars.SCRIPTS_DIR }}
          MY_ISSUE_LABEL: ${{ secrets.MY_ISSUE_LABEL }}
